### ISSUE TITLE
GREpractice_JGSG needs a code review

### ISSUE THREAD

**Issue by SarahGillespie** [jcg0105/QuizBuilder#8]
The GREpractice_JGSG is ready for a code review!

Could you please proofread to make sure the code that I've added is purposeful, has sufficient comments, and generally is smart coding logic?

This Medium article is helpful but very in-depth about the code review that I think would be most useful for this Java file. https://medium.com/palantir/code-review-best-practices-19e02780015f

**Comment by jcg0105** [comment]
Resolved; 
Changes:
+ updated comments to reflect file change from CSV to txt
+ question sources moved to credits
+ creating new Question object now uses fluent building design to increase readability & easier editing
+ Question toString function now includes if there is a source or not
+ Question toString function updated to use switch case for readability
- removed repetitive comments & comments that overexplained
- removed description in 1st line of .txt files
- removed getters in Question class
Overall code is well structured and comments are used in a sufficient manner! I would suggest removing articles from variable names and possibly shortening some variable names to keep the program concise (while making sure names are understood).
The change from CSV to txt was a smart idea! The first line being descriptors for the order gave me errors in the code so I removed it, but the new getters in the class should explain it well enough so it isn't necessary while we're using it (although when adding more questions I'm sure it's helpful; maybe there's a way to ignore lines in txt documents?).
